name: release

on:
  push:
    branches: [ "main" ]

jobs:
  pre-release:
    name: "Pre-release (Linux)"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Install Ninja"
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: "Build environment (Linux)"
        run: |
          chmod +x ./build.sh
          ./build.sh release

      - name: "List build directory contents"
        run: |
          ls -R ./release

      - name: "Upload artifacts (Linux)"
        uses: actions/upload-artifact@v2
        with:
          name: linux-artifacts
          path: |
            ./release/zura

  get-version:
    name: "Get Version"
    runs-on: ubuntu-latest
    needs: [pre-release]

    steps:
      - name: "Download Linux artifacts"
        uses: actions/download-artifact@v2
        with:
          name: linux-artifacts

      - name: "Get version"
        id: get-version
        run: |
          echo "::set-output name=artifact_path::$(cat version.txt)"

      - name: "Print version"
        run: |
          echo "Version: ${{ steps.get-version.outputs.artifact_path }}"

      - name: "Upload version"
        uses: actions/upload-artifact@v2
        with:
          name: version

  combine-artifacts:
    name: "Combine Artifacts"
    runs-on: ubuntu-latest
    needs: [pre-release]

    steps:
      - name: "Download Linux artifacts"
        uses: actions/download-artifact@v2
        with:
          name: linux-artifacts
          path: ./linux-artifacts

      - name: "List downloaded artifacts"
        run: |
          ls -R ./linux-artifacts  # Add this step to verify the artifacts

      - name: "Upload combined artifacts"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "release ${{ steps.get-version.outputs.artifact_path }}"
          prerelease: false
          files: |
            ./linux-artifacts/zura