name: Pre release

on:
  push:
    branches: [ "main" ]

jobs:
  pre-release:
    name: "Pre release"
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v3"
      - name: "Build environment"
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Release"
          files: |
            ./build/zura
            ./README.md
            ./LICENSE